### PR TITLE
Graphprotocol/use subgraph for data

### PR DESCRIPTION
**Pull request by davekaj**
Hey Guys, 

Here is a PR that refractors the app to receive data from The Graph. 

I reworked the subgraph so that it provides both user centric data (what we showed in the meeting we had) and historical data (which I have added in). Right now it is mostly just the historical data that is implemented, so that we could mimic what existed before. 

Per day and per event stats are available. Just check out https://thegraph.com/explorer/subgraph/graphprotocol/uniswap to see what is possible. Also, if there is any other stats that are desired, please let us know!

Here are a few notes on the implementation:
- Apollo and GraphQl are used to query The Graph Hosted Service, replacing the previous REST queries
- Sometimes the data is slightly different from the loanscan api, for aggregated data. For the most part it is accurate, but it depends on how each app is dividing up each day. It seems like it is sometimes ~10 seconds behind ours when a new tx comes in. But if you look at the chart graphs they follow each other exactly. Mainly its the 24 hour % change that is different. It might be that both of the APIs follow _roughly_ 24 hours. Ours is based on the the latest event, and then the closest event from 24 hours away, so it could end up being 23.8 hours ago. I am not sure how the other api implements this, but it results in slight differences. 
- For the most part I just swapped out the queries, and tried to keep the app functions as close as possible to before 
- The signs flipped for displaying transactions - as I believe before they were incorrect before. (please correct me if I am wrong)
- I just noticed it seems to always have slightly more volume that the previous API data, and sometimes the volume is much bigger. I am going to look into this right away, and post what I figure out 

Here are some things we added inside the chart:
- Added in ROI each day
- USD price of the token (based on oracle price of Uniswap USDC, TUSD, and DAI)
- Added in transaction count each day (swap txs and liquidity txs)
- Other data can be added, just let us know

You can view the live UI here: https://uniswap.now.sh/

### CODE REVIEW

**Comment by haydenadams** [comment]
@davekaj This looks amazing! Thanks so much for your work

We're ultimately hoping to add an overview page as well that allows you to see pools ranked by liquidity / 24hr volume. Potentially that feature could be added to `Uniswap -> exchanges -> orderBy (volume, liquidity, id, symbol)` or something?

**Comment by davekaj** [comment]
Yeah that's basically how the query would work!

https://github.com/Uniswap/uniswap-info/blob/aedf5738dfc340472eb67f43990438b5a66f3c0b/src/apollo/queries.js#L54 This query returns the list of exchanges for the dropdown menu in order of volume (as you will notice right now DAI always shows up, because lately it has more volume than MKR). So by modifying this query a bit for the exact data needed this could be done!

**Comment by davekaj** [comment]
Ah I believe I figured out the extra volume issue. I accidentally was including adding and removing of liquidity as volume. thats why it was always slightly bigger, and then the days it was a lot bigger was when someone added or removed a lot of liquidity. 

pushing a fix to the subgraph now

**Comment by davekaj** [comment]
hey FYI I am working on building a Front page UI for uniswap.info. I actually hooked up all the queries already, I am just waiting on one of our designers to help me make the front page look like the existing page with the charts!

**Comment by haydenadams** [comment]
@davekaj thats awesome! Let me know when its ready :)

**Comment by davekaj** [comment]
@haydenadams hey the overview page is done! you can check it out here https://uniswap-thegraph.now.sh/

let us know what you think!

**Comment by NoahZinsmeister** [comment]
@davekaj thanks so much for this PR! the changes look really great overall.

right now i'm sorting out the branch structure and release process for this repo, after which i'll merge this pr and deploy it to a subdomain (probably `the-graph.uniswap.info`). when that's done, i'll do a closer review to see what other information we might want/etc., and go from there!

we're still working out exactly what to do re. urls (including this PR, there are now 3 versions of the info site 🤪). eventually, we'd like to settle on one version that we (=uniswap) actively maintain at `uniswap.info`, and then allow anyone with sufficient interest/resources to maintain their own sub-domain (`*.uniswap.info`). so, let's punt on whether this will be the canonical version (though i'm pretty optimistic it could be!)

**Comment by davekaj** [comment]
No problem!

And okay, sounds good! keep me posted for when you deploy it to a subdomain!

**Comment by NoahZinsmeister** [comment]
will do, it'll likely be later today!

**Comment by NoahZinsmeister** [comment]
@davekaj this PR is now merged into the [`the-graph` branch](https://github.com/Uniswap/uniswap-info/tree/the-graph) (which is also the base against which future PRs should be made).

it's also live at [the-graph.uniswap.info](https://the-graph.uniswap.info/).

thanks again for this, looking forward to more collaboration!

**Pull request merged**
